[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
cmds = []

[start]
cmd = 'php artisan config:clear && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'
